### ISSUE TITLE
Can we make libcxxwrap-julia a header-only library?

### ISSUE THREAD

**Issue by metab0t** [JuliaInterop/libcxxwrap-julia#104]
I an wondering whether we can make libcxxwrap-julia a header-only library just like pybind11. The cpp files only contain ~700 lines of code.

Header-only library will make it easier to distribute and maybe we can get rid of libcxxwrap_julia_jll?

```bash
$ tokei include src
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 C++                     4          807          686            7          114
 C++ Header             11         3821         3092          147          582
===============================================================================
 Total                  15         4628         3778          154          696
===============================================================================
```

**Comment by barche** [comment]
Unfortunately this is not possible (as far as I can tell) because we use functionality from the Julia runtime in libjulia, so linking against that is needed. Also the STL part compiles in a series of predefined types, it would be hard to consolidate these lists if each wrapped library defined its own list. Although that would be better if it could be made to work.

**Comment by metab0t** [comment]
Thanks for explanation!
There are some shared components that should live in libcxxwrap_julia, including global module registry and type mapping.
